version: "3"

services:
  deploy:
    image: "${IMAGE_TAG}"
    volumes:
      - ${WORK_SPACE}:c:/solution/workspace
    environment:
      MAVEN_DEPLOY_TARGET: ${MAVEN_DEPLOY_TARGET}
      AZURE_SP_APP_ID: ${AZURE_SP_APP_ID}
      AZURE_SP_TENANT: ${AZURE_SP_TENANT}
      AZURE_SP_PASSWD: ${AZURE_SP_PASSWD}

networks:
  default:
    external:
      name: nat
