# https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'vs2017-win2016'

# For a private pool, in this example, named Private requiring the capability of PowerShell
#pool: 
#  name: Azure
#  demands: PowerShell

# or pool with no demands
#pool: Azure

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    automation\processor\entry.bat $(Build.BuildId) $(Build.SourceBranchName) staging@$(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
