---
project:
  key: YOUREXISTINGPROJECTKEY
  plan:
    key: YOURNEWPLANKEY
    name: Plan using CDAF Build and Package
stages:
  - jobs:
      - scripts:
          - "automation\\provisioning\\runner.bat automation\\processor\\buildPackage.ps1 ${bamboo.buildNumber} ${bamboo.repository.revision.number}"
        interpreter: cmd.exe
        requirements:
          - container
        artifacts:
          - name: Package
            path: '*.zip'
          - name: TasksLocal
            path: 'TasksLocal/**'
