---
version: 2

plan:
  project-key: REF
  key: CDAFW
  name: CDAf Public Contribute

stages:
  - Build Stage:
    - Build Job

Build Job:
  tasks:
    - script:
        - "automation\\processor\\entry.bat ${bamboo.buildNumber} ${bamboo.repository.branch.name}"

  artifacts:
    - name: Package
      pattern: '*.zip'
      shared: true
    - name: TasksLocal
      pattern: 'TasksLocal/**'
      shared: true

---
version: 2

deployment:
  name: CDAFW
  source-plan: REF-CDAFW

release-naming:
  next-version-name: 2.0.1.${bamboo.buildNumber}

environments:
  - NO_PROP
  - WINDOWS
  - CDAF_DEPLOY

NO_PROP:
  triggers:
    - build-success
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - "${bamboo.build.working.directory}\\TasksLocal\\delivery.bat ${bamboo.deploy.environment} ${bamboo.deploy.release}"

WINDOWS:
  triggers:
    - environment-success: NO_PROP
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - "${bamboo.build.working.directory}\\TasksLocal\\delivery.bat ${bamboo.deploy.environment} ${bamboo.deploy.release}"

CDAF_DEPLOY:
  triggers:
    - environment-success: WINDOWS
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - 'Remove-Item -Force -Recurse ~/.cdaf -ErrorAction SilentlyContinue'
        - '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
        - '(New-Object System.Net.WebClient).DownloadFile("https://codeload.github.com/cdaf/windows/zip/master", "$PWD\cdaf.zip")'
        - 'Add-Type -AssemblyName System.IO.Compression.FileSystem'
        - '[System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD\cdaf.zip", "$PWD")'
        - 'Move-Item .\windows-master\automation\ ~/.cdaf'
        - '~/.cdaf/remote/capabilities.ps1'
      interpreter: powershell        
