version: "3"
services:
    target:
        image: "${TARGET_TAG}"
        volumes:
          - ${WORK_SPACE}:c:/solution/workspace
        environment:
          MAVEN_ARTIFACT_TOKEN: ${MAVEN_ARTIFACT_TOKEN}
    test:
        image: "${TEST_TAG}"
        volumes:
          - ${WORK_SPACE}:c:/solution/workspace
        links:
          - target:target
        depends_on:
          - target

networks:
  default:
    external:
      name: nat
